name: Simple Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Create ECR repositories if they don't exist
      run: |
        aws ecr describe-repositories --repository-names codingal-backend --region $AWS_REGION || \
        aws ecr create-repository --repository-name codingal-backend --region $AWS_REGION
        aws ecr describe-repositories --repository-names codingal-frontend --region $AWS_REGION || \
        aws ecr create-repository --repository-name codingal-frontend --region $AWS_REGION

    - name: Build and push backend
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        cd backend
        docker build -t $ECR_REGISTRY/codingal-backend:$IMAGE_TAG .
        docker tag $ECR_REGISTRY/codingal-backend:$IMAGE_TAG $ECR_REGISTRY/codingal-backend:latest
        docker push $ECR_REGISTRY/codingal-backend:$IMAGE_TAG
        docker push $ECR_REGISTRY/codingal-backend:latest

    - name: Build and push frontend
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        cd frontend
        docker build -t $ECR_REGISTRY/codingal-frontend:$IMAGE_TAG .
        docker tag $ECR_REGISTRY/codingal-frontend:$IMAGE_TAG $ECR_REGISTRY/codingal-frontend:latest
        docker push $ECR_REGISTRY/codingal-frontend:$IMAGE_TAG
        docker push $ECR_REGISTRY/codingal-frontend:latest

    - name: Deploy infrastructure with Terraform
      working-directory: ./aws-deployment/terraform
      run: |
        terraform init
        terraform plan -var="db_password=${{ secrets.DB_PASSWORD }}"
        terraform apply -auto-approve -var="db_password=${{ secrets.DB_PASSWORD }}"

    - name: Output deployment info
      run: |
        echo "🚀 Deployment completed successfully!"
        echo "Backend ECR: $(aws ecr describe-repositories --repository-names codingal-backend --query 'repositories[0].repositoryUri' --output text)"
        echo "Frontend ECR: $(aws ecr describe-repositories --repository-names codingal-frontend --query 'repositories[0].repositoryUri' --output text)"
        echo "Check AWS ECS console for your application URL"
