name: Terraform Deploy to AWS

on:
  push:
    branches: [ main ]
    paths:
      - 'aws-deployment/**'
      - 'backend/**'
      - 'frontend/**'
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.13.4

    - name: Terraform Init
      working-directory: ./aws-deployment/terraform
      run: terraform init

    - name: Terraform Plan
      working-directory: ./aws-deployment/terraform
      run: terraform plan -var="db_password=${{ secrets.DB_PASSWORD }}"

    - name: Terraform Apply
      working-directory: ./aws-deployment/terraform
      run: terraform apply -auto-approve -var="db_password=${{ secrets.DB_PASSWORD }}"

    - name: Get outputs
      working-directory: ./aws-deployment/terraform
      run: |
        echo "VPC ID: $(terraform output -raw vpc_id)"
        echo "Backend ECR URL: $(terraform output -raw ecr_backend_repository_url)"
        echo "Frontend ECR URL: $(terraform output -raw ecr_frontend_repository_url)"
        echo "RDS Endpoint: $(terraform output -raw rds_endpoint)"
        echo "ALB DNS: $(terraform output -raw alb_dns_name)"
